# Allows for the definition of PR and Issue /commands
name: "ðŸ“Ÿ Slash Command Dispatcher"

on:
  issue_comment:
    types:
      - created

jobs:
  call:
    uses: WorkingRobot/jellyfin-meta-plugins/.github/workflows/command-dispatch.yaml@master
    secrets:
      token: .
